<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Project.Core\Project.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentMigrator" Version="6.2.0" />
    <PackageReference Include="FluentMigrator.Runner" Version="6.2.0" />
    <PackageReference Include="linq2db" Version="5.4.1" />
    <PackageReference Include="linq2db.EntityFrameworkCore" Version="9.0.0" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="5.2.2" />
    <PackageReference Include="MySqlConnector" Version="2.4.0" />
    <PackageReference Include="Npgsql" Version="9.0.1" />
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="9.0.0" />
    <PackageReference Include="System.Net.NameResolution" Version="4.3.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Mapping\Builders\Common\" />
  </ItemGroup>

</Project>
